import { describe, it, expect } from "vitest";
import {
  decideLedgerExport,
  simulateWorstCaseAgeHours,
  DEFAULT_REFRESH_THRESHOLD_HOURS
} from "../../src/lib/approvalLedgerScheduleDecision.js";

/**
 * T-0434: the approval ledger (`tools/board/approval-ledger.json`) is regenerated by hand and
 * expires on a wall clock -- `checkApprovalProvenanceDrift.js` fails the whole PR when the
 * committed ledger is both stale (older than `BOARD_APPROVAL_LEDGER_STALE_HOURS`, 24h) and
 * load-bearing. This blocked #440 (46h old) and #439 (62.9h old) in two consecutive days, neither
 * PR touching approvals at all.
 *
 * Two naive fixes both fail (see the card and this module's own docstring):
 *   - commit on every scheduled run -- `generated_at` always differs, so every run is a commit.
 *   - commit only when the cards changed -- a quiet week never refreshes `generated_at`, and the
 *     gate fails exactly as it does today.
 *
 * `decideLedgerExport` is the chosen policy ("refresh-before-it-bites"): commit when the cards
 * changed, OR when the committed ledger is already older than a threshold well under 24h. These
 * tests prove both halves of that -- it doesn't churn on an unrelated run, and it can't let the
 * ledger reach the gate's own threshold while the scheduled job is actually running.
 */
describe("decideLedgerExport", () => {
  it("commits when the cards changed, regardless of how fresh the ledger still is", () => {
    const decision = decideLedgerExport({ cardsChanged: true, ledgerAgeHours: 0.1 });
    expect(decision).toEqual({ shouldCommit: true, reason: "cards-changed" });
  });

  it("does not commit when nothing changed and the ledger is still within the refresh threshold", () => {
    const decision = decideLedgerExport({
      cardsChanged: false,
      ledgerAgeHours: 5,
      refreshThresholdHours: 12
    });
    expect(decision).toEqual({ shouldCommit: false, reason: "fresh-no-change" });
  });

  it("commits on an unchanged card set once the ledger crosses the refresh threshold -- this is the forced refresh that keeps a quiet week from aging past the gate", () => {
    const decision = decideLedgerExport({
      cardsChanged: false,
      ledgerAgeHours: 12.01,
      refreshThresholdHours: 12
    });
    expect(decision).toEqual({ shouldCommit: true, reason: "refresh-threshold" });
  });

  it("treats exactly-at-threshold as still fresh (strict greater-than, not greater-or-equal)", () => {
    const decision = decideLedgerExport({
      cardsChanged: false,
      ledgerAgeHours: 12,
      refreshThresholdHours: 12
    });
    expect(decision).toEqual({ shouldCommit: false, reason: "fresh-no-change" });
  });

  it("commits when there is no prior age to compare against (Infinity -- no committed ledger yet)", () => {
    const decision = decideLedgerExport({ cardsChanged: false, ledgerAgeHours: Infinity });
    expect(decision).toEqual({ shouldCommit: true, reason: "refresh-threshold" });
  });

  it("commits on a NaN age (unparseable generated_at) rather than treating it as fresh -- fail toward refreshing, not toward trusting an unreadable timestamp", () => {
    const decision = decideLedgerExport({ cardsChanged: false, ledgerAgeHours: NaN });
    expect(decision).toEqual({ shouldCommit: true, reason: "refresh-threshold" });
  });

  it("defaults refreshThresholdHours to 12 when not given", () => {
    expect(DEFAULT_REFRESH_THRESHOLD_HOURS).toBe(12);
    const fresh = decideLedgerExport({ cardsChanged: false, ledgerAgeHours: 11.9 });
    const stale = decideLedgerExport({ cardsChanged: false, ledgerAgeHours: 12.1 });
    expect(fresh.shouldCommit).toBe(false);
    expect(stale.shouldCommit).toBe(true);
  });
});

describe("simulateWorstCaseAgeHours", () => {
  it("never lets the ledger's age exceed threshold + interval over a long quiet period, on schedule", () => {
    const { maxAgeHours, runCount } = simulateWorstCaseAgeHours({
      intervalHours: 4,
      refreshThresholdHours: 12,
      totalHours: 240 // 10 days, no card ever changes
    });
    expect(runCount).toBe(60);
    expect(maxAgeHours).toBeLessThanOrEqual(12 + 4);
    expect(maxAgeHours).toBeLessThan(24); // BOARD_APPROVAL_LEDGER_STALE_HOURS
  });

  it("stays under the 24h gate even when a single scheduled run is missed entirely", () => {
    const { maxAgeHours } = simulateWorstCaseAgeHours({
      intervalHours: 4,
      refreshThresholdHours: 12,
      totalHours: 240,
      missedRunTicks: new Set([3]) // the run at hour 12 silently doesn't happen
    });
    expect(maxAgeHours).toBeLessThanOrEqual(12 + 2 * 4);
    expect(maxAgeHours).toBeLessThan(24);
  });

  it("does not commit on every run during a quiet period -- bounded churn, not the every-run-is-a-commit failure mode", () => {
    const { commitCount, runCount } = simulateWorstCaseAgeHours({
      intervalHours: 4,
      refreshThresholdHours: 12,
      totalHours: 240
    });
    // Roughly one commit per threshold window (240h / 12h = 20), never one per run (60).
    expect(commitCount).toBeLessThan(runCount / 2);
    expect(commitCount).toBeGreaterThan(0);
  });

  it("two consecutive missed runs still stay under the 24h gate -- Persistent=true only needs to catch up by the next tick, not instantly", () => {
    const { maxAgeHours } = simulateWorstCaseAgeHours({
      intervalHours: 4,
      refreshThresholdHours: 12,
      totalHours: 240,
      missedRunTicks: new Set([3, 4]) // hours 12 and 16 both silently skipped
    });
    expect(maxAgeHours).toBe(20);
    expect(maxAgeHours).toBeLessThan(24);
  });

  it("names the actual limit of this design: enough consecutive missed runs breaks the under-24h bound", () => {
    // Four consecutive missed runs = a 16h outage with no catch-up in between. This is the
    // honest edge of "refresh-before-it-bites": the policy bounds staleness against the
    // SCHEDULE, not against the box being off for most of a day. A box down that long already
    // shows up as silence across every other timer in this ops suite (board-db-backup,
    // board-integrity-check, etc.), not just this one -- see the card's own tradeoff note.
    const { maxAgeHours } = simulateWorstCaseAgeHours({
      intervalHours: 4,
      refreshThresholdHours: 12,
      totalHours: 240,
      missedRunTicks: new Set([3, 4, 5, 6]) // hours 12, 16, 20, 24 all silently skipped
    });
    expect(maxAgeHours).toBe(28);
    expect(maxAgeHours).toBeGreaterThan(24);
  });

  it("pins the real edge: three consecutive missed runs already exhausts the margin to the 24h gate, not four", () => {
    // A prior round's README claimed the design survives three consecutive misses and only
    // breaks at four. That undercounts: a gap positioned where the run that WOULD have forced a
    // refresh is itself missed (ticks 3-5, the same alignment the specs above already use) drives
    // the worst case to exactly 24h -- the gate's own BOARD_APPROVAL_LEDGER_STALE_HOURS threshold,
    // with zero hours of margin left, not comfortably under it. This is the gap "straddling the
    // gate boundary" the fix-round asked this suite to pin, rather than just restating one
    // convenient offset.
    const { maxAgeHours } = simulateWorstCaseAgeHours({
      intervalHours: 4,
      refreshThresholdHours: 12,
      totalHours: 240,
      missedRunTicks: new Set([3, 4, 5]) // hours 12, 16, 20 all silently skipped
    });
    expect(maxAgeHours).toBe(24);
  });

  it("a gap positioned right after a publish is the SAFE case -- position, not just gap length, determines the margin", () => {
    // Same gap length (3 consecutive misses) as the spec above, but positioned immediately after
    // the natural first refresh (which lands at hour 16 in this schedule) instead of over the run
    // that would have forced one. The slack already built into the refresh cadence absorbs this
    // gap entirely -- worst case never rises above the steady-state 16h high-water mark. Proves
    // the arithmetic depends on WHERE an outage falls relative to the schedule, not only how long
    // it lasts, so a single offset can't stand in for "the" worst case.
    const { maxAgeHours } = simulateWorstCaseAgeHours({
      intervalHours: 4,
      refreshThresholdHours: 12,
      totalHours: 240,
      missedRunTicks: new Set([5, 6, 7]) // hours 20, 24, 28 -- right after the hour-16 refresh
    });
    expect(maxAgeHours).toBe(16);
    expect(maxAgeHours).toBeLessThan(24);
  });
});
