"""Generic submit -> poll -> fetch pattern shared by every generation backend.

Extracted from `tools/comfy-client` (T-0071) into its own package so the two
concrete backends -- `comfy_client.comfyui_client.ComfyUIClient` (ComfyUI,
driving `AssetAgent`) and `audio_agent.audio_client.AudioClient` (ACE-Step,
driving `AudioAgent`, T-0082) -- share this scaffolding instead of each
reimplementing submit/poll/fetch/timeout. Both packages depend on this one
(`pip install -e ../gen-client-base`) rather than either depending on the
other.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any


class GenerationClient(ABC):
    @abstractmethod
    def submit(self, workflow: dict[str, Any]) -> str:
        """Submit a rendered request payload; return a backend job id."""

    @abstractmethod
    def wait_for_completion(self, job_id: str, timeout: float, poll_interval: float) -> Any:
        """Wait until `job_id` completes; return the backend's completed-job payload.

        Backends that complete synchronously inside `submit` (no separate
        poll endpoint) may implement this as a pass-through -- see
        `audio_agent.audio_client.AudioClient` for that case.
        """

    @abstractmethod
    def fetch_output(self, job_result: Any) -> bytes:
        """Fetch the generated bytes referenced by a completed-job payload."""

    def generate(
        self, workflow: dict[str, Any], timeout: float = 300.0, poll_interval: float = 1.0
    ) -> bytes:
        """submit -> wait_for_completion -> fetch_output: the `generate` arrow
        of `recipe -> generate -> descend -> validate -> provenance`
        (13-asset-pipeline.md §1)."""
        job_id = self.submit(workflow)
        result = self.wait_for_completion(job_id, timeout=timeout, poll_interval=poll_interval)
        return self.fetch_output(result)
