add_test( [==[PgNoteRepo CRUD round-trip]==] /home/dennieseth/dev/assembled-board/worktrees/T-0046/server/build2/note_repo_tests [==[--test-case=PgNoteRepo CRUD round-trip]==])
set_tests_properties( [==[PgNoteRepo CRUD round-trip]==] PROPERTIES WORKING_DIRECTORY /home/dennieseth/dev/assembled-board/worktrees/T-0046/server/build2 LABELS)
add_test( [==[PgNoteRepo rejects bad template_id via FK]==] /home/dennieseth/dev/assembled-board/worktrees/T-0046/server/build2/note_repo_tests [==[--test-case=PgNoteRepo rejects bad template_id via FK]==])
set_tests_properties( [==[PgNoteRepo rejects bad template_id via FK]==] PROPERTIES WORKING_DIRECTORY /home/dennieseth/dev/assembled-board/worktrees/T-0046/server/build2 LABELS)
add_test( [==[PgNoteRepo rejects bad slot_a via FK]==] /home/dennieseth/dev/assembled-board/worktrees/T-0046/server/build2/note_repo_tests [==[--test-case=PgNoteRepo rejects bad slot_a via FK]==])
set_tests_properties( [==[PgNoteRepo rejects bad slot_a via FK]==] PROPERTIES WORKING_DIRECTORY /home/dennieseth/dev/assembled-board/worktrees/T-0046/server/build2 LABELS)
add_test( [==[NoteRepo fetch is keyed on (archetype_id, anchor_tag) — no radius]==] /home/dennieseth/dev/assembled-board/worktrees/T-0046/server/build2/note_repo_tests [==[--test-case=NoteRepo fetch is keyed on (archetype_id\, anchor_tag) — no radius]==])
set_tests_properties( [==[NoteRepo fetch is keyed on (archetype_id, anchor_tag) — no radius]==] PROPERTIES WORKING_DIRECTORY /home/dennieseth/dev/assembled-board/worktrees/T-0046/server/build2 LABELS)
set( note_repo_tests_TESTS [==[PgNoteRepo CRUD round-trip]==] [==[PgNoteRepo rejects bad template_id via FK]==] [==[PgNoteRepo rejects bad slot_a via FK]==] [==[NoteRepo fetch is keyed on (archetype_id, anchor_tag) — no radius]==])
