if(EXISTS "/home/dennieseth/dev/assembled-board/worktrees/T-0046/server/build2/note_repo_tests_tests-b858cb2.cmake")
  include("/home/dennieseth/dev/assembled-board/worktrees/T-0046/server/build2/note_repo_tests_tests-b858cb2.cmake")
else()
  add_test(note_repo_tests_NOT_BUILT-b858cb2 note_repo_tests_NOT_BUILT-b858cb2)
endif()
