"""Append T-0101 + T-0204 one-shot WAV provenance entries to ASSET_PROVENANCE.md."""

import pathlib

REPO = pathlib.Path(__file__).parents[3]  # audio/ -> src/ -> assets/ -> T-0204/
PROV_FILE = REPO / "ASSET_PROVENANCE.md"

ENTRIES = [
    (
        "assets/final/audio/footstep_concrete.wav",
        "T-0101",
        "N/A -- procedurally generated by FOOTSTEP_CONCRETE recipe in "
        "assets/src/audio/src/sfx_synth/recipes.py, not AI-generated. "
        "Deterministic DSP synthesis: 2-layer resonant bandpass-filtered white noise "
        "(150 Hz thud q=3.0, 3200 Hz scuff q=2.5 at -8 dB), physically modelling a "
        "concrete floor strike. EBU R128 -16.0 LUFS (gameplay_sfx, never ducked). WAV PCM_16 "
        "44.1 kHz. sha256: 5305a3c9525b7d81d9b5aacde995d498ed9367a3b5feb5d04db72bf1fb2f3697.",
        "Recipe: FOOTSTEP_CONCRETE in sfx_synth/recipes.py. "
        "Reproducible: sfx-synth render footstep_concrete.",
        "101",
    ),
    (
        "assets/final/audio/switch_click.wav",
        "T-0101",
        "N/A -- procedurally generated by SWITCH_CLICK recipe, not AI-generated. "
        "2-layer white noise (4200 Hz press q=6.0, 3600 Hz release q=6.0 at onset 0.045s "
        "at -4 dB), modelling a mechanical toggle. EBU R128 -18.0 LUFS (world_sfx). WAV PCM_16 "
        "44.1 kHz. sha256: 06893e5be370b76872130c0b67d476af7d892987f541ef3e7215b75162896ef7.",
        "Recipe: SWITCH_CLICK in sfx_synth/recipes.py.",
        "102",
    ),
    (
        "assets/final/audio/door.wav",
        "T-0101",
        "N/A -- procedurally generated by DOOR recipe, not AI-generated. "
        "5-layer pink noise descending resonant sweep (900->700->550->450 Hz creak at 80ms "
        "intervals, q=5.0) + white-noise thud (130 Hz q=2.5 at onset 0.42s), modelling a "
        "door creak and frame impact. EBU R128 -18.0 LUFS (world_sfx). WAV PCM_16 44.1 kHz. "
        "sha256: 176e59a4acf8bd855be589bbc42e070f1403d1c7c571dc5f94734891008b23d7.",
        "Recipe: DOOR in sfx_synth/recipes.py.",
        "103",
    ),
    (
        "assets/final/audio/item_pickup.wav",
        "T-0101",
        "N/A -- procedurally generated by ITEM_PICKUP recipe, not AI-generated. "
        "3-layer pink noise ascending arc (900->1400->2100 Hz, q=10.0, 35ms apart), "
        "modelling a positive collectible cue. EBU R128 -18.0 LUFS (world_sfx). "
        "WAV PCM_16 44.1 kHz. "
        "sha256: 8f992f65896dff88541c395db298092dd601978f9f63f4f9ddc8e114efb3ea74.",
        "Recipe: ITEM_PICKUP in sfx_synth/recipes.py.",
        "104",
    ),
    (
        "assets/final/audio/footstep_walk.wav",
        "T-0204",
        "N/A -- procedurally generated by FOOTSTEP_WALK recipe, not AI-generated. "
        "2-layer white noise (140 Hz soft thud q=3.5 at -2 dB, 2800 Hz gentle scuff q=2.0 "
        "at -10 dB), modelling a careful measured walk step. Distinct from footstep_run: "
        "lower energy, narrower scuff, softer. EBU R128 -16.0 LUFS (gameplay_sfx, never "
        "ducked -- fairness P-5). WAV PCM_16 44.1 kHz. "
        "sha256: 12b82bd2f4e5fa0aed3dcddb4e258f9cb7098b7c71af8be4c12756458768ffb3.",
        "Recipe: FOOTSTEP_WALK in sfx_synth/recipes.py.",
        "105",
    ),
    (
        "assets/final/audio/footstep_run.wav",
        "T-0204",
        "N/A -- procedurally generated by FOOTSTEP_RUN recipe, not AI-generated. "
        "3-layer white noise (120 Hz heavy thud q=2.5 at +3 dB, 4000 Hz sharp scuff q=2.0 "
        "at -5 dB, 650 Hz flex crack q=2.0 at -12 dB onset 0.008s), modelling full "
        "body-weight impact at running speed. Distinct from footstep_walk: heavier, louder, "
        "more layers. EBU R128 -16.0 LUFS (gameplay_sfx, never ducked -- fairness P-5). "
        "WAV PCM_16 44.1 kHz. "
        "sha256: 9ebf445708416e962a21b02fcb771b72d857a973dee4514105261b761821e5eb.",
        "Recipe: FOOTSTEP_RUN in sfx_synth/recipes.py.",
        "106",
    ),
    (
        "assets/final/audio/item_leave.wav",
        "T-0204",
        "N/A -- procedurally generated by ITEM_LEAVE recipe, not AI-generated. "
        "3-layer pink noise descending arc (2100->1400->900 Hz, q=10.0, 35ms apart), "
        "mirror-inverse of item_pickup, modelling setting an item down. EBU R128 -18.0 LUFS "
        "(world_sfx). WAV PCM_16 44.1 kHz. "
        "sha256: 09dfbcdcf9df7d6a59cd0b5518e85480852678b94a014d578413adc34916260c.",
        "Recipe: ITEM_LEAVE in sfx_synth/recipes.py.",
        "107",
    ),
    (
        "assets/final/audio/telegraph_watcher.wav",
        "T-0204",
        "N/A -- procedurally generated by TELEGRAPH_WATCHER recipe, not AI-generated. "
        "3-layer white noise (5200 Hz lock-on click q=8.0, 2400 Hz lens-mechanism harmonic "
        "q=6.0 at -5 dB onset 0.012s, 4800 Hz confirm sub-click q=7.0 at -8 dB onset 0.04s), "
        "modelling the Watcher surveillance-orb detection cue. EBU R128 -16.0 LUFS (gameplay_sfx "
        "-- detection-warning fairness channel P-5, NEVER DUCKED). WAV PCM_16 44.1 kHz. "
        "sha256: 400b1326ae82323c767941792f43721938cf71520d48ae192fbcc285b428a618.",
        "Recipe: TELEGRAPH_WATCHER in sfx_synth/recipes.py.",
        "108",
    ),
    (
        "assets/final/audio/telegraph_sound.wav",
        "T-0204",
        "N/A -- procedurally generated by TELEGRAPH_SOUND recipe, not AI-generated. "
        "3-layer pink noise mid-range wave-crest ripple (800 Hz primary q=4.0, 1600 Hz "
        "overtone q=4.0 at -4 dB onset 0.03s, 1200 Hz trailing crest q=3.5 at -8 dB "
        "onset 0.07s), modelling the Sound wave-band entity detection cue. EBU R128 "
        "-16.0 LUFS (gameplay_sfx -- fairness P-5, NEVER DUCKED). WAV PCM_16 44.1 kHz. "
        "sha256: 3d1bc58d21a6d06b3bdd419b45dd31668113f339b94efc975982aa49a6bc2c88.",
        "Recipe: TELEGRAPH_SOUND in sfx_synth/recipes.py.",
        "109",
    ),
    (
        "assets/final/audio/telegraph_still_air.wav",
        "T-0204",
        "N/A -- procedurally generated by TELEGRAPH_STILL_AIR recipe, not AI-generated. "
        "3-layer pink noise atmospheric column resonance (200 Hz column mode q=6.0, 420 Hz "
        "overtone q=5.0 at -4 dB, 900 Hz airy presence q=3.5 at -12 dB onset 0.02s), "
        "modelling the Still Air pillar entity detection cue. Slower attack, longer tail "
        "than Watcher/Sound. EBU R128 -16.0 LUFS (gameplay_sfx -- fairness P-5, NEVER "
        "DUCKED). WAV PCM_16 44.1 kHz. "
        "sha256: c59a00b285cbdeeabf20998de8d5fe67b42f4fceff88c71062350ba1c484de24.",
        "Recipe: TELEGRAPH_STILL_AIR in sfx_synth/recipes.py.",
        "110",
    ),
]

lines = ["\n"]
for asset, task, model_col, prompt_col, seed_col in ENTRIES:
    lines.append(
        f"| `{asset}` ({task}) "
        f"| {model_col} "
        f"| N/A "
        f"| {prompt_col} "
        f"| seed={seed_col} |\n"
    )

with open(PROV_FILE, "a") as f:
    f.writelines(lines)

print(f"Appended {len(ENTRIES)} entries to {PROV_FILE}")
