#!/usr/bin/env python3
"""
Read-only re-derivation of the staged board-assets-export tree from the live
board. Never writes anything to the board itself -- only reads via its HTTP
API (GET /api/tasks, GET /api/tasks/:id/attachments/:filename) -- and never
writes outside EXPORT_ROOT.

Source of truth for "which tasks produced stageable assets": each card's
`attachments` metadata array, as returned by the board API. That is the one
fully-mechanical, no-judgment signal the board gives us, so it's the only
thing this script auto-stages. This works unchanged whether the board is
running in db-store or fs-store mode (BOARD_TASK_STORE) -- the API is the
abstraction boundary, so the stager never needs to know or care whether a
card's attachments live under tasks/attachments/<id>/ (fs mode) or
~/.local/share/assembled-board/attachments/<id>/ (db mode).

Any task directory already under EXPORT_ROOT whose MANIFEST.md does NOT carry
the AUTO_MARKER comment is treated as "pinned": content already curated (by a
human or an earlier one-off pass) and is left byte-for-byte untouched. Pinned
manifests are still parsed so their task counts toward index.json. To let the
stager manage a task's manifest going forward, delete the manifest (or the
whole task dir) and let this script regenerate it from attachments.
"""
import hashlib
import json
import os
import re
import shutil
import sys
import tempfile
from datetime import date, datetime, timezone
from pathlib import Path
from urllib.parse import quote

import requests

HOME = Path(os.environ["HOME"])
EXPORT_ROOT = Path(os.environ.get("BOARD_ASSETS_EXPORT_ROOT", "/mnt/f/PetProjects/board-assets-export"))
STAGE_TMP = EXPORT_ROOT / ".stage-tmp"

API_BASE = os.environ.get("BOARD_API_BASE", "http://127.0.0.1:4173").rstrip("/")
API_TIMEOUT = float(os.environ.get("BOARD_ASSETS_API_TIMEOUT", "15"))

AUTO_MARKER = "<!-- auto-generated by board-assets-stage.py"

MAX_TASK_BYTES = 500 * 1024 * 1024  # ~500MB per-task guard
BLOCKLIST_EXT = {".safetensors", ".ckpt", ".pt", ".pth", ".bin", ".onnx"}

TYPE_MAP = {
    ".png": "image", ".jpg": "image", ".jpeg": "image", ".gif": "image",
    ".webp": "image", ".bmp": "image", ".tga": "image", ".svg": "image",
    ".wav": "audio", ".mp3": "audio", ".flac": "audio", ".ogg": "audio",
    ".mp4": "video", ".webm": "video", ".mov": "video",
    ".md": "doc", ".txt": "doc", ".pdf": "doc", ".rst": "doc",
    ".json": "result", ".csv": "result", ".tsv": "result",
    ".yaml": "result", ".yml": "result",
}
RESERVED_DIRNAMES = {"_rclone_logs", ".stage-tmp"}

# Pinned/untracked entries whose canonical Notion row title (matched by
# Drive folder id, not name) does not match what's mechanically derivable
# from the manifest heading. Keep in sync with the actual Notion row title.
UNTRACKED_TITLE_OVERRIDES = {
    "UNTRACKED-keyart": "UNTRACKED — Signal Tower key art",
}


def log(msg):
    print(f"[stage] {msg}", file=sys.stderr)


def api_get(path, **kwargs):
    url = f"{API_BASE}{path}"
    try:
        resp = requests.get(url, timeout=API_TIMEOUT, **kwargs)
    except requests.exceptions.RequestException as e:
        raise RuntimeError(f"board API request failed: GET {url}: {e}") from e
    if resp.status_code >= 400:
        raise RuntimeError(f"board API request failed: GET {url}: HTTP {resp.status_code} {resp.text[:200]}")
    return resp


def load_all_cards():
    """Fetches all cards from the board API. Returns {taskId: task-dict}."""
    tasks = api_get("/api/tasks").json()
    return {t["id"]: t for t in tasks}


def classify(filename: str) -> str:
    ext = Path(filename).suffix.lower()
    if ".provenance." in filename or ".meta." in filename:
        # Notion's Asset types multi-select only allows
        # image/audio/doc/result/code/other -- no bespoke "metadata" value.
        return "other"
    return TYPE_MAP.get(ext, "other")


def human_bytes(n: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024 or unit == "GB":
            return f"{n:.1f} {unit}" if unit != "B" else f"{n} B"
        n /= 1024
    return f"{n} B"


def sha1_of(path: Path) -> str:
    h = hashlib.sha1()
    h.update(path.read_bytes())
    return h.hexdigest()


def dirs_identical(a: Path, b: Path) -> bool:
    """True if a and b contain the same set of files with identical content."""
    if not a.is_dir() or not b.is_dir():
        return False
    a_files = {p.name: p for p in a.iterdir() if p.is_file()}
    b_files = {p.name: p for p in b.iterdir() if p.is_file()}
    if set(a_files) != set(b_files):
        return False
    for name, pa in a_files.items():
        pb = b_files[name]
        if pa.stat().st_size != pb.stat().st_size:
            return False
        if sha1_of(pa) != sha1_of(pb):
            return False
    return True


def extract_existing_summary(manifest_path: Path) -> str | None:
    if not manifest_path.exists():
        return None
    text = manifest_path.read_text(encoding="utf-8", errors="replace")
    m = re.search(r"## Summary\n\n(.*?)\n\n## ", text, re.S)
    if m:
        return m.group(1).strip()
    return None


def is_pinned(task_dir: Path) -> bool:
    manifest = task_dir / "MANIFEST.md"
    if not manifest.exists():
        return False
    return AUTO_MARKER not in manifest.read_text(encoding="utf-8", errors="replace")


def build_manifest_text(tid, fm, files, summary_text) -> str:
    title = fm.get("title", tid)
    status = fm.get("status", "unknown")
    agent = fm.get("agent", "unknown")
    branch = fm.get("branch") or "(none recorded on card)"
    pr = fm.get("pr") or "(none recorded on card)"
    deliverable_type = fm.get("deliverable_type") or "(unspecified)"
    depends_on = fm.get("depends_on") or []
    depends_str = ", ".join(depends_on) if depends_on else "(none)"

    rows = []
    total = 0
    for name, size in sorted(files.items()):
        total += size
        rows.append(f"| `{name}` | {classify(name)} | {human_bytes(size)} |")
    files_table = "\n".join(rows) if rows else "| (none) | | |"

    return f"""# {tid} — {title}

| Field | Value |
|---|---|
| Task ID | {tid} |
| Status | {status} |
| Producing agent | {agent} |
| Branch | {branch} |
| PR | {pr} |
| Deliverable type | {deliverable_type} |
| Depends on | {depends_str} |

## Summary

{summary_text}

## Files ({len(files)})

| Filename | Type | Size |
|---|---|---|
{files_table}

**Total: {len(files)} files, {human_bytes(total)}**

Source: staged via the board API (`{API_BASE}`) from card `{tid}`'s attachments metadata.

{AUTO_MARKER} — do not hand-edit, edits will be overwritten. Delete this
     comment line (converting the file to a pinned/manual manifest) to make
     the stager leave this task's directory alone on future runs. -->
"""


def stage_attachment_task(tid, fm):
    """Returns True if this task dir was (re)written or is already in sync."""
    fm_attachments = fm.get("attachments") or []
    by_name = {a.get("filename"): a for a in fm_attachments if isinstance(a, dict) and a.get("filename")}
    if not by_name:
        return False

    wanted = sorted(by_name.keys())

    candidates = {}
    skipped = []
    total = 0
    for name in wanted:
        meta = by_name[name]
        if Path(name).suffix.lower() in BLOCKLIST_EXT:
            skipped.append((name, "blocklisted extension"))
            continue
        size = meta.get("size")
        if not isinstance(size, (int, float)):
            size = None
        if size is not None and total + size > MAX_TASK_BYTES:
            skipped.append((name, "would exceed 500MB per-task guard"))
            continue
        candidates[name] = size
        if size is not None:
            total += size

    dest_dir = EXPORT_ROOT / tid
    if is_pinned(dest_dir):
        log(f"{tid}: pinned manifest exists, leaving directory untouched")
        return True

    tmp_dir = STAGE_TMP / tid
    if tmp_dir.exists():
        shutil.rmtree(tmp_dir)
    tmp_dir.mkdir(parents=True)

    files = {}
    for name in candidates:
        url = f"/api/tasks/{quote(tid, safe='')}/attachments/{quote(name, safe='')}"
        try:
            resp = api_get(url)
        except RuntimeError as e:
            skipped.append((name, f"download failed: {e}"))
            continue
        data = resp.content
        (tmp_dir / name).write_bytes(data)
        files[name] = len(data)

    if skipped:
        for name, reason in skipped:
            log(f"WARN: {tid}: skipping {name} ({reason})")

    if not files:
        shutil.rmtree(tmp_dir, ignore_errors=True)
        log(f"WARN: {tid}: no attachments could be staged (all skipped/failed)")
        return False

    total = sum(files.values())

    existing_summary = extract_existing_summary(dest_dir / "MANIFEST.md")
    summary_text = existing_summary or (
        f"Auto-staged from {len(files)} card attachment(s) on {tid} ({fm.get('title', tid)})."
    )
    (tmp_dir / "MANIFEST.md").write_text(
        build_manifest_text(tid, fm, files, summary_text), encoding="utf-8"
    )

    if dirs_identical(tmp_dir, dest_dir):
        shutil.rmtree(tmp_dir)
        return True

    dest_dir.mkdir(parents=True, exist_ok=True)
    # swap: remove stale files not in the new set, then move new/changed ones in
    keep_names = set(files) | {"MANIFEST.md"}
    for existing in list(dest_dir.iterdir()):
        if existing.name not in keep_names:
            existing.unlink()
    for item in tmp_dir.iterdir():
        shutil.copy2(item, dest_dir / item.name)
    shutil.rmtree(tmp_dir)
    log(f"{tid}: staged {len(files)} file(s), {human_bytes(total)}")
    return True


def parse_manifest_for_index(task_dir: Path, cards: dict):
    manifest = task_dir / "MANIFEST.md"
    tid = task_dir.name
    text = manifest.read_text(encoding="utf-8", errors="replace") if manifest.exists() else ""

    def table_field(label):
        m = re.search(rf"\|\s*{re.escape(label)}\s*\|\s*(.*?)\s*\|", text)
        return m.group(1).strip() if m else None

    title = table_field("Task ID")
    m = re.match(rf"^#\s*{re.escape(tid)}\s*—\s*(.*)$", text, re.M)
    card_title = m.group(1).strip() if m else tid

    live = cards.get(tid)
    status = live.get("status") if live else table_field("Status")
    agent = live.get("agent") if live else table_field("Producing agent")
    if live and live.get("title"):
        card_title = live["title"]
    if tid in UNTRACKED_TITLE_OVERRIDES:
        card_title = UNTRACKED_TITLE_OVERRIDES[tid]
    if status is None:
        status = table_field("Status") or "unknown"
    if agent is None:
        agent = table_field("Producing agent") or "unknown"

    summary = extract_existing_summary(manifest) or ""
    summary = re.sub(r"\s+", " ", summary).strip()

    # walk recursively: some pinned/legacy dirs nest files under a subfolder
    # (e.g. T-0072's corpus/), while auto-managed dirs are always flat.
    files = [
        p for p in task_dir.rglob("*")
        if p.is_file() and p.name != "MANIFEST.md" and not p.name.startswith(".")
    ]
    asset_types = sorted({classify(p.name) for p in files})
    total_bytes = sum(p.stat().st_size for p in files)

    return {
        "taskId": tid,
        "cardTitle": card_title,
        "status": status,
        "agent": agent,
        "summary": summary,
        "assetTypes": asset_types,
        "assetCount": len(files),
        "totalBytes": total_bytes,
        "relPath": tid,
    }


def write_index(cards):
    EXPORT_ROOT.mkdir(parents=True, exist_ok=True)
    task_dirs = sorted(
        p for p in EXPORT_ROOT.iterdir()
        if p.is_dir() and not p.name.startswith(".") and p.name not in RESERVED_DIRNAMES
    )
    tasks = []
    for d in task_dirs:
        if not (d / "MANIFEST.md").exists():
            log(f"WARN: {d.name} has no MANIFEST.md, skipping from index")
            continue
        tasks.append(parse_manifest_for_index(d, cards))

    total_bytes = sum(t["totalBytes"] for t in tasks)
    index = {
        "generated_at": date.today().isoformat(),
        "generated_at_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": f"Board API ({API_BASE}) -- staged by board-assets-stage.py",
        "totals": {
            "task_count": len(tasks),
            "file_count": sum(t["assetCount"] for t in tasks),
            "total_bytes": total_bytes,
            "total_mb": round(total_bytes / (1024 * 1024), 2),
        },
        "notes": [
            "Tasks with an auto-generated MANIFEST.md (marker comment present) are "
            "re-derived every run from the board API's card attachments metadata -- the "
            "only fully-mechanical asset signal the board exposes.",
            "Tasks whose MANIFEST.md lacks that marker are 'pinned': staged once by hand "
            "or an earlier one-off pass, and intentionally left untouched by the stager.",
            "Model weights (.safetensors/.ckpt/.pt/.pth/.bin/.onnx) are never staged.",
            "Per-task staged size is capped at ~500MB; oversized files are skipped and "
            "logged, not silently dropped.",
        ],
        "tasks": tasks,
    }

    out = EXPORT_ROOT / "index.json"
    new_text = json.dumps(index, indent=2) + "\n"
    if not out.exists() or out.read_text(encoding="utf-8") != new_text:
        tmp = out.with_suffix(".json.tmp")
        tmp.write_text(new_text, encoding="utf-8")
        tmp.replace(out)
        log("index.json updated")
    else:
        log("index.json unchanged")


def main():
    EXPORT_ROOT.mkdir(parents=True, exist_ok=True)
    STAGE_TMP.mkdir(parents=True, exist_ok=True)

    try:
        cards = load_all_cards()
    except RuntimeError as e:
        log(f"ERROR: could not reach board API at {API_BASE}: {e}")
        log("ERROR: aborting rather than risk staging against stale/partial data")
        sys.exit(1)

    for tid, fm in sorted(cards.items()):
        if not fm.get("attachments"):
            continue
        try:
            stage_attachment_task(tid, fm)
        except Exception as e:
            log(f"ERROR staging {tid}: {e} (leaving any existing staged copy untouched)")

    if STAGE_TMP.is_dir():
        shutil.rmtree(STAGE_TMP, ignore_errors=True)

    write_index(cards)


if __name__ == "__main__":
    main()
