"""Generic submit -> poll -> fetch pattern shared by every generation backend.

ComfyUI (`comfyui_client.ComfyUIClient`) is the only implementation today,
but the shape is deliberately backend-agnostic so the audio pipeline's
`AudioAgent` (T-0082, docs/PLAN.md Phase 7 DRY note) can subclass
`GenerationClient` for its own backend (Stable Audio Open / ACE-Step)
without duplicating the submit/poll/fetch/timeout scaffolding.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any


class GenerationClient(ABC):
    @abstractmethod
    def submit(self, workflow: dict[str, Any]) -> str:
        """Submit a rendered workflow graph; return a backend job id."""

    @abstractmethod
    def wait_for_completion(self, job_id: str, timeout: float, poll_interval: float) -> Any:
        """Poll until `job_id` completes; return the backend's completed-job payload."""

    @abstractmethod
    def fetch_output(self, job_result: Any) -> bytes:
        """Fetch the generated bytes referenced by a completed-job payload."""

    def generate(
        self, workflow: dict[str, Any], timeout: float = 300.0, poll_interval: float = 1.0
    ) -> bytes:
        """submit -> wait_for_completion -> fetch_output: the `generate` arrow
        of `recipe -> generate -> descend -> validate -> provenance`
        (13-asset-pipeline.md §1)."""
        job_id = self.submit(workflow)
        result = self.wait_for_completion(job_id, timeout=timeout, poll_interval=poll_interval)
        return self.fetch_output(result)
