#!/usr/bin/env python3
"""T-0340 calibration: pose-fidelity IoU + identity-stability histogram,
measured against what is actually committed (docs/decision-log.md DL-31).

Not a generator and not a gate -- a one-shot report script. Run it, read
the numbers it prints, and keep the committed output
(`docs/decision-log.md` DL-31's table) as the record; nothing here writes
provenance or promotes anything.

Measures two real, on-disk artifacts against the new
`asset_gate.art.check_pose_fidelity` / `check_identity_stability`:

  - `assets/final/character/player_walk_sheet_hybrid.png` (T-0259 attempt 4,
    DL-26's own committed walk) -- the rig-predicted silhouette for each of
    its 8 frames comes from `pose_rig_walk_T0259.walk_keypoints_for_frame`,
    the SAME keypoints `gen_hybrid_walk_T0259.py` conditioned ControlNet
    with, rendered as capsules via `asset_gate.art.render_rig_silhouette`
    (`_POSE_LIMBS`' topology, reused unchanged from
    `gen_arm_a_idle_T0228.py` -- not re-authored).
  - `assets/final/character/player_idle_sheet_hybrid_T0252.png` (the shipped
    idle) -- for context only. Idle is generated by band-translating one
    SDXL frame (`char_gen.synth_entities`), not by a keypoint rig, so there
    is no rig-predicted silhouette to compare it against; this script only
    reports its existing (unchanged) frame_delta_range under the idle cap.

The session-13 sequential-chained negative control is NOT measured here --
that candidate's pixels live under a gitignored `assets/out/` path and were
never committed (assets/out/ is reproducible-not-committed by design; see
`.claude/rules/assets.md`), so there is nothing on this disk to load. Its
entry in DL-31's table is a synthetic reproduction of the review's own
qualitative description (a torso colour fade that shrinks the silhouette
without moving it), built and measured directly in
`tools/asset-gate/tests/test_art.py::test_identity_stability_catches_drift_that_frame_consistency_missed`
-- that test's numbers are quoted in DL-31 as-is, not re-derived here.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

_CHARACTER_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _CHARACTER_DIR.parents[2]
for _extra in (
    _REPO_ROOT / "tools" / "asset-gate" / "src",
    _CHARACTER_DIR,
):
    if str(_extra) not in sys.path:
        sys.path.insert(0, str(_extra))

import numpy as np  # noqa: E402
from asset_gate.art import (  # noqa: E402
    check_identity_stability,
    check_pose_fidelity,
    render_rig_silhouette,
)
from gen_arm_a_idle_T0228 import _POSE_KEYPOINTS_NORM, _POSE_LIMBS  # noqa: E402
from PIL import Image  # noqa: E402
from pose_rig_walk_T0259 import FRAME_COUNT, walk_keypoints_for_frame  # noqa: E402

_CHARACTER_FINAL_DIR = _REPO_ROOT / "assets" / "final" / "character"
WALK_SHEET = _CHARACTER_FINAL_DIR / "player_walk_sheet_hybrid.png"
IDLE_SHEET = _CHARACTER_FINAL_DIR / "player_idle_sheet_hybrid_T0252.png"
IDLE_PROVENANCE = _CHARACTER_FINAL_DIR / "player_idle_sheet_hybrid_T0252.provenance.json"

CELL_PX = 48
COLS, ROWS = 4, 2
BACKGROUND_INDEX = 0
# The capsule half-width, in the same 48px-cell pixel space the sheet is
# indexed in -- a stick-figure-with-thickness approximation of the body,
# not an attempt at anatomical accuracy. Loosely bracketed by the rig's own
# shoulder width at this scale (~8px across two shoulders => ~4px half-width
# for a torso-scale limb); legs/arms are thinner in a real sprite than the
# torso, so 2.5px is a conservative middle value applied uniformly, the same
# way `_POSE_LIMBS` gives every limb equal line width at 384px.
CAPSULE_RADIUS_PX = 2.5

# Torso box: the quadrilateral spanned by both shoulders (joints 2, 5) and
# both hips (joints 8, 11) in `_POSE_KEYPOINTS_NORM`, scaled to the 48px
# cell -- fixed across frames (the torso is what identity-stability is
# checking for staying put, so the box must not itself move with the gait).
_R_SHOULDER, _L_SHOULDER, _R_HIP, _L_HIP = 2, 5, 8, 11


def _torso_region(cell_px: int) -> tuple[int, int, int, int]:
    xs = [_POSE_KEYPOINTS_NORM[j][0] for j in (_R_SHOULDER, _L_SHOULDER, _R_HIP, _L_HIP)]
    ys = [_POSE_KEYPOINTS_NORM[j][1] for j in (_R_SHOULDER, _L_SHOULDER, _R_HIP, _L_HIP)]
    x0, x1 = round(min(xs) * cell_px), round(max(xs) * cell_px)
    y0, y1 = round(min(ys) * cell_px), round(max(ys) * cell_px)
    return x0, y0, x1, y1


def _predicted_silhouette(points_norm: dict[int, tuple[float, float]], cell_px: int) -> np.ndarray:
    limbs = [
        (
            (points_norm[a][0] * cell_px, points_norm[a][1] * cell_px),
            (points_norm[b][0] * cell_px, points_norm[b][1] * cell_px),
        )
        for a, b, _colour in _POSE_LIMBS
    ]
    return render_rig_silhouette(size=cell_px, limbs=limbs, radius=CAPSULE_RADIUS_PX)


def _split_cells(sheet: Image.Image, cols: int, rows: int, cell_px: int) -> list[Image.Image]:
    return [
        sheet.crop((c * cell_px, r * cell_px, c * cell_px + cell_px, r * cell_px + cell_px))
        for r in range(rows)
        for c in range(cols)
    ]


def calibrate_walk_sheet() -> dict:
    sheet = Image.open(WALK_SHEET)
    cells = _split_cells(sheet, COLS, ROWS, CELL_PX)
    assert len(cells) == FRAME_COUNT, f"expected {FRAME_COUNT} frames, sheet has {len(cells)}"

    pose_ious = []
    for i, cell in enumerate(cells):
        points = walk_keypoints_for_frame(i, FRAME_COUNT)
        predicted = _predicted_silhouette(points, CELL_PX)
        result = check_pose_fidelity(
            cell, predicted, background_index=BACKGROUND_INDEX, min_iou=0.0
        )
        pose_ious.append(result.details["iou"])

    torso_region = _torso_region(CELL_PX)
    identity_distances = []
    pairs = [(i, (i + 1) % FRAME_COUNT) for i in range(FRAME_COUNT)]
    for a, b in pairs:
        result = check_identity_stability(
            cells[a],
            cells[b],
            background_index=BACKGROUND_INDEX,
            region=torso_region,
            max_histogram_distance=1.0,
        )
        identity_distances.append(result.details["distance"])

    return {
        "sheet": str(WALK_SHEET.relative_to(_REPO_ROOT)),
        "frame_count": FRAME_COUNT,
        "capsule_radius_px": CAPSULE_RADIUS_PX,
        "torso_region": torso_region,
        "pose_fidelity_iou_per_frame": pose_ious,
        "pose_fidelity_range": [min(pose_ious), max(pose_ious)],
        "identity_stability_distance_per_pair": identity_distances,
        "identity_stability_range": [min(identity_distances), max(identity_distances)],
    }


def calibrate_idle_sheet_context() -> dict:
    provenance = json.loads(IDLE_PROVENANCE.read_text())
    return {
        "sheet": str(IDLE_SHEET.relative_to(_REPO_ROOT)),
        "note": "idle is band-translated from one SDXL frame, not rig-authored -- no "
        "pose-fidelity/identity-stability numbers to measure; reported for context only",
        "frame_delta_range": provenance["frame_delta_range"],
        "motion_class_recorded": provenance.get("motion_class"),
    }


def main() -> None:
    report = {
        "walk_T0259_attempt4": calibrate_walk_sheet(),
        "idle_T0252_context": calibrate_idle_sheet_context(),
    }
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
