#!/usr/bin/env python3
"""Round-2 identity-view curation — T-0248 (HANDOFF §24-a).

Curates the 34 candidates generated by gen_identity_views_T0248.py
(assets/out/identity_views_v2/, gitignored) down to the committed
assets/src/character/identity_refs_v2/ training set + curation manifest.

Every candidate was visually inspected (see KEPT/DROPPED below). Costume
consistency held across the whole batch -- the IP-Adapter anchor + style
LoRA combination reliably reproduced the institutional-green-coat
costume -- but camera angle mostly stayed front-facing regardless of the
prompted angle (a known IP-Adapter limitation: it also carries some
composition/pose bias from the reference image, not just style). This is
recorded honestly rather than papered over: captions describe what is
actually depicted in each kept image, not the aspirational prompt that
generated it, since training on a caption that doesn't match its image
would teach the LoRA a false association. Genuine pose/framing variety
(walking stride, crouch attempt, arm gestures, close medium shots, hood
up/down) is real and kept; camera-angle variety (profile/back) mostly did
not materialize and is not claimed.

Usage (from the repo root):
    python3 assets/src/character/curate_identity_views_T0248.py

Writes:
    assets/src/character/identity_refs_v2/ref_NNN.png   (29 files)
    assets/src/character/identity_refs_v2/ref_NNN.txt   (29 caption files)
    assets/src/character/identity_curation_manifest_T0248.json
"""

from __future__ import annotations

import hashlib
import json
import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
CANDIDATES_DIR = REPO_ROOT / "assets" / "out" / "identity_views_v2"
REFS_DIR = Path(__file__).resolve().parent / "identity_refs_v2"
MANIFEST_PATH = Path(__file__).resolve().parent / "identity_curation_manifest_T0248.json"
ANCHOR_REF_PATH = Path(__file__).resolve().parent / "identity_refs" / "ref_002.png"

CONCEPT_SHEET_PATH = (
    REPO_ROOT / "assets" / "src" / "concept" / "player_character_concept_sheet_v1.png"
)
EXPECTED_CONCEPT_HASH = "4f82e3c42dbc0d4ba6960144f6507c5d6dbd7fb0945c54558532d922c9c0251b"

TRIGGER_TOKEN = "sbrutalistplayer"
COSTUME_ID = "institutional_green_coat_v1"

CAPTION_TEMPLATE = (
    "{trigger} character, Soviet brutalist institutional green hooded coat, "
    "white gloves, dark boots, {view}, flat colour concept illustration, "
    "grey background"
)

# view_id -> actual observed view/pose (what is genuinely depicted, not the
# aspirational generation prompt -- see module docstring).
KEPT: dict[str, str] = {
    "v001": "front view, standing idle, arms at sides",
    "v002": "front view, standing idle, arms at sides",
    "v004": "three-quarter front view, standing idle, belt strap detail",
    "v005": "three-quarter front view, standing idle, shoulder sling detail",
    "v006": "front view, standing idle, capped head",
    "v007": "front view, standing idle, hooded head",
    "v008": "front view, standing idle, goggled head",
    "v009": "front view, standing idle, patterned leg wrap",
    "v010": "front view, standing idle",
    "v012": "front view, standing idle, visible face",
    "v013": "front view, standing idle",
    "v015": "front view, standing idle, capped head with insignia",
    "v016": "front view, standing idle, low composition crop",
    "v017": "front view, standing idle, cropped composition",
    "v018": "front view, standing idle, insignia patch",
    "v019": "front view, standing idle",
    "v020": "front view, standing idle, arm extended in pointing gesture",
    "v021": "front view, standing idle, insignia patch",
    "v022": "front view, standing idle, belt detail",
    "v023": "front view, standing idle, insignia patch, cropped composition",
    "v024": "front view, standing idle, capped head with visor detail",
    "v025": "front view, standing idle",
    "v026": "front view, standing idle, shoulder patch",
    "v027": "front view, standing idle",
    "v028": "front view, standing idle, visible eyes",
    "v029": "front view, standing idle, coat hem detail",
    "v030": "front view, standing idle",
    "v032": "front view, standing idle, cropped waist-up composition",
    "v033": "front view, standing idle, visible face, cropped waist-up composition",
}

DROPPED: list[dict] = [
    {
        "id": "v003",
        "reason": "near-duplicate of v001/v002 (same front-view-standing-idle prompt/costume, "
        "no new view or pose information) -- redundant, not a curation exception",
    },
    {
        "id": "v011",
        "reason": "near-duplicate of v010 (same prompt, no new view/pose information) -- redundant",
    },
    {
        "id": "v014",
        "reason": "head render artifact (rectangular block in place of a head) -- not "
        "costume-representative, would teach the LoRA a malformed head",
    },
    {
        "id": "v031",
        "reason": "head design drift: rendered a rigid rectangular visor/helmet instead of "
        "the soft hood established across every other candidate -- exactly the kind of "
        "silhouette drift this card's hard-curation pass exists to catch",
    },
    {
        "id": "v034",
        "reason": "near-duplicate of v001/v002 (same front-view-standing-idle prompt/costume, "
        "no new view or pose information) -- redundant",
    },
]


def sha256_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def curate() -> dict:
    concept_hash = sha256_of(CONCEPT_SHEET_PATH)
    if concept_hash != EXPECTED_CONCEPT_HASH:
        raise RuntimeError(
            f"concept sheet hash mismatch: got {concept_hash}, expected {EXPECTED_CONCEPT_HASH}"
        )
    anchor_hash = sha256_of(ANCHOR_REF_PATH)

    REFS_DIR.mkdir(parents=True, exist_ok=True)
    refs: list[dict] = []
    for i, (view_id, view) in enumerate(sorted(KEPT.items()), start=1):
        src_png = CANDIDATES_DIR / f"{view_id}.png"
        src_provenance = json.loads((CANDIDATES_DIR / f"{view_id}.provenance.json").read_text())
        ref_id = f"ref_{i:03d}"
        caption = CAPTION_TEMPLATE.format(trigger=TRIGGER_TOKEN, view=view)

        dest_png = REFS_DIR / f"{ref_id}.png"
        shutil.copyfile(src_png, dest_png)
        (REFS_DIR / f"{ref_id}.txt").write_text(caption)

        refs.append(
            {
                "id": ref_id,
                "source_candidate": view_id,
                "view": view,
                "caption": caption,
                "costume_id": COSTUME_ID,
                "seed": src_provenance["seed"],
                "generation_prompt_id": src_provenance["prompt_id"],
            }
        )

    manifest = {
        "curation_version": "1.0",
        "card": "T-0248",
        "round": "2 (HANDOFF §24-a)",
        "selection_doc": "assets/src/character/CANONICAL_COSTUME_SELECTION_T0248.md",
        "source_sheet": "assets/src/concept/player_character_concept_sheet_v1.png",
        "concept_hash": concept_hash,
        "concept_card": "T-0209",
        "anchor_ref": "assets/src/character/identity_refs/ref_002.png",
        "anchor_ref_hash": anchor_hash,
        "costume_id": COSTUME_ID,
        "trigger_token": TRIGGER_TOKEN,
        "generator": "assets/src/character/gen_identity_views_T0248.py",
        "curator": "assets/src/character/curate_identity_views_T0248.py",
        "selection_rationale": (
            "34 candidates generated (IP-Adapter conditioned on the single fixed ref_002 "
            "anchor + style LoRA, varied prompt/seed per candidate, no ControlNet). All 34 "
            "held costume consistency (same green coat, white gloves, dark boots) -- the "
            "hypothesis this card tests. 5 were dropped: 3 near-duplicate front-view-idle "
            "repeats with no new view/pose information, and 2 for head-region rendering "
            "defects (a block-shaped head artifact, and a rigid visor/helmet that broke "
            "from the soft-hood silhouette established everywhere else). The kept 29 are "
            "not uniform camera angles -- IP-Adapter mostly kept generations front-facing "
            "regardless of the prompted angle -- but they are genuinely varied in pose, "
            "framing, and incidental detail (walking stride, arm gestures, hood up/down, "
            "close medium shots), which is real information the 12-image v1 set (2 camera "
            "angles x mirrors) did not have."
        ),
        "refs": refs,
        "dropped": DROPPED,
    }
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n")
    return manifest


def main() -> None:
    manifest = curate()
    summary = {"kept": len(manifest["refs"]), "dropped": len(manifest["dropped"])}
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
